### ISSUE TITLE
CBCT exposure parameters

### ISSUE THREAD

**Issue by gammawing** [winkpoke/console#4]
CBCT exposure parameters still can be modified in the process of exposure
<img width="272" alt="exposure parameters" src="https://user-images.githubusercontent.com/22463106/76486329-0a3fa980-645a-11ea-837c-77b8de65b7ce.PNG">

**Comment by winkpoke** [comment]
This issue will be taking care when rewriting the CBCT business logic and put it into a mod.

**Comment by winkpoke** [comment]
fix in commit e66cd7
